# Generated by Django 4.0 on 2022-01-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_devicemanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(default=True, max_length=120),
        ),
    ]
